import ar from './ar.json'
import de_DE from './de_DE.json'
import es from './es.json'
import fr_FR from './fr_FR.json'
import ja_JP from './ja_JP.json'
import ko_KR from './ko_KR.json'
import pt_PT from './pt_PT.json'
import ru_RU from './ru_RU.json'
import tr_TR from './tr_TR.json'
import uk_UA from './uk_UA.json'
import vi_VN from './vi_VN.json'
// Generated by scripts/extract-translations.ts, do not edit.
import zh_CN from './zh_CN.json'
import zh_TW from './zh_TW.json'

export const translations: Record<string, Record<string, string>> = {
  zh_CN,
  zh_TW,
  fr_FR,
  es,
  de_DE,
  ru_RU,
  vi_VN,
  ko_KR,
  tr_TR,
  ar,
  uk_UA,
  ja_JP,
  pt_PT,
}
