// Builds src/i18n/<locale>.json from the gettext catalogs of the host: only
// the strings this plugin uses. Strings the host does not have come from
// scripts/new-strings.json.
//
//   bun scripts/extract-translations.ts [--po-dir <dir>]
//
// The catalog directory defaults to $NGINX_UI_LANGUAGE_DIR, then to
// ../../nginx-ui/app/src/language next to this repository.
import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { extractMsgids, parsePo } from './po'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')

// Locales the host ships, see app/i18n.json. English is the source language.
const LOCALES = ['zh_CN', 'zh_TW', 'fr_FR', 'es', 'de_DE', 'ru_RU', 'vi_VN', 'ko_KR', 'tr_TR', 'ar', 'uk_UA', 'ja_JP', 'pt_PT']
// Every string must be translated for these, the others may fall back to English.
const REQUIRED = ['zh_CN', 'zh_TW', 'ja_JP']

function argValue(name: string): string | undefined {
  const index = process.argv.indexOf(name)
  return index >= 0 ? process.argv[index + 1] : undefined
}

function sourceFiles(dir: string): string[] {
  const files: string[] = []
  for (const name of readdirSync(dir)) {
    const path = join(dir, name)
    if (statSync(path).isDirectory()) {
      if (name !== 'i18n')
        files.push(...sourceFiles(path))
    }
    else if (/\.(?:ts|vue)$/.test(name)) {
      files.push(path)
    }
  }
  return files
}

const poDir = resolve(argValue('--po-dir') ?? process.env.NGINX_UI_LANGUAGE_DIR ?? join(root, '../../nginx-ui/app/src/language'))
if (!existsSync(poDir)) {
  console.error(`catalog directory not found: ${poDir}`)
  process.exit(2)
}

const msgids = [...new Set(sourceFiles(join(root, 'src')).flatMap(file => extractMsgids(readFileSync(file, 'utf8'))))].sort()

const extra: Record<string, Record<string, string>> = JSON.parse(readFileSync(join(root, 'scripts/new-strings.json'), 'utf8'))

mkdirSync(join(root, 'src/i18n'), { recursive: true })

let failed = false
for (const locale of LOCALES) {
  const catalog = parsePo(readFileSync(join(poDir, `${locale}.po`), 'utf8'))
  const messages: Record<string, string> = {}
  const missing: string[] = []

  for (const msgid of msgids) {
    // A translation equal to the source needs no entry, the source is shown anyway.
    const translated = extra[msgid]?.[locale] ?? catalog.get(msgid)
    if (translated === undefined)
      missing.push(msgid)
    else if (translated !== msgid)
      messages[msgid] = translated
  }

  writeFileSync(join(root, `src/i18n/${locale}.json`), `${JSON.stringify(messages, null, 2)}\n`)
  // eslint-disable-next-line no-console
  console.log(`${locale}: ${Object.keys(messages).length} of ${msgids.length} strings`)

  if (missing.length > 0 && REQUIRED.includes(locale)) {
    failed = true
    console.error(`  missing in ${locale}:\n${missing.map(id => `    ${JSON.stringify(id)}`).join('\n')}`)
  }
}

const indexLines = [
  '// Generated by scripts/extract-translations.ts, do not edit.',
  ...LOCALES.map(locale => `import ${locale} from './${locale}.json'`),
  '',
  'export const translations: Record<string, Record<string, string>> = {',
  ...LOCALES.map(locale => `  ${locale},`),
  '}',
  '',
]
writeFileSync(join(root, 'src/i18n/index.ts'), indexLines.join('\n'))

process.exit(failed ? 1 : 0)
